Copied!
Resolution:
Use except Exception: instead of except as a best practice for catching exceptions and handling them comprehensively.

For instance, if the existing code is:

1
2
except:
    print("Error")
Copied!
You can change this to:

1
2
except Exception as e:
    print(f"Error: {e}")
Copied!

JS Hint (Javascript) Linting errors:
1. If you receive one or more errors as listed below:
1
2
3
4
5
6
7
8
9
'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').
'async functions' is only available in ES8 (use 'esversion: 8').
'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
'template literal syntax' is only available in ES6 (use 'esversion: 6').
Copied!
Resolution:
Add the line below at the start of the file(s) where this error is reported:

1
/*jshint esversion: 8 */
Copied!

2. Error:
1
['xxxxxx'] is better written in dot notation.
Copied!
Resolution:
This issue arises when Dictionary/JSON key-value pairs are formatted as key[value]. To resolve it, switch the format to key.value.
For example, if you have the existing code as: keyA['valA'], update it to keyA.valA.
